version: '2.4'
services:
  incnv-frontend:
    image: saowwapark/incnv-frontend:latest
    container_name: incnv-frontend
    restart: always
    networks:
      - incnv-network
  incnv-backend:
    image: saowwapark/incnv-backend:latest
    container_name: incnv-backend
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - DB_HOST=incnv-databases
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - UPDATE_BIO_DATA_SCHEDULE="0 0 * * *"
    networks:
      - incnv-network
    volumes:
      - datasources-volume:/usr/src/app/volumes/datasources_volume
      - analysis-results-volume:/usr/src/app/volumes/analysis_results_volume
    depends_on:
      incnv-databases:
        condition: service_healthy
  incnv-databases:
    image: sakkayaphab/incnv-databases:latest
    container_name: incnv-databases
    restart: always
    networks:
      - incnv-network
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - databases-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=rootpassword
    ports:
      - 7004:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u","root","--password=rootpassword"]
      timeout: 20s
      retries: 10
  incnv-reverse-proxy:
    image: sakkayaphab/incnv-reverse-proxy:latest
    container_name: incnv-reverse-proxy
    restart: always
    ports:
      - 7000:80
    networks:
      - incnv-network
    depends_on:
      incnv-databases:
        condition: service_healthy

volumes:
  databases-volume:
  datasources-volume:
  analysis-results-volume:

networks:
  incnv-network: {}