name: Authen Docker Hub

on:
  push:
    branches:
      - CNV-614  # Trigger on push to main branch
env:
  NODE_VERSION: '20'
jobs:
  create-frontend-image:
    runs-on: ubuntu-latest

    steps:
      - name: Push Docker images to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
