name: Build and Deploy Docker Images

on:
  push:
    branches:
      - CNV-614  # Trigger on push to main branch
    paths:
      - 'app.json'  # Trigger only when app.json is changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Read current app.json version
        id: read-current-app-json
        run: |
          current_version=$(jq -r '.version' ./app.json)
          echo "current_version=${current_version}" >> $GITHUB_ENV

      - name: Fetch tags from remote
        run: git fetch --tags

      - name: Check if tag already exists
        id: tag-check
        run: |
          if git rev-parse "v${{ env.current_version }}" >/dev/null 2>&1; then
            echo "Tag v${{ env.current_version }} already exists."
            echo "::set-output name=tag_exists::true"
          else
            echo "Tag v${{ env.current_version }} does not exist."
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create tag if not exists
        if: steps.tag-check.outputs.tag_exists == 'false'
        run: |
          git tag "v${{ env.current_version }}"
          git push origin "v${{ env.current_version }}"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend project
        run: npm run build
        working-directory: ./frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Build backend project
        run: npm run build
        working-directory: ./backend

      - name: Build and push frontend Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t saowwapark/incnv-frontend:v${{ env.current_version }} -t saowwapark/incnv-frontend:latest ./frontend --push

      - name: Build and push backend Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t saowwapark/incnv-backend:v${{ env.current_version }} -t saowwapark/incnv-backend:latest ./backend --push

      - name: Push Docker images to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push saowwapark/incnv-frontend:v${{ env.current_version }}
          docker push saowwapark/incnv-frontend:latest
          docker push saowwapark/incnv-backend:v${{ env.current_version }}
          docker push saowwapark/incnv-backend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
