name: Authen Docker Hub

on:
  push:
    branches:
      - CNV-614  # Trigger on push to main branch
env:
  NODE_VERSION: '20'
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current app.json version
        id: read-current-app-json
        run: |
          current_version=$(jq -r '.version' ./app.json)
          echo "current_version=${current_version}" >> $GITHUB_ENV
          echo "::set-output name=current_version::${current_version}"
          echo -e "\033[32mCurrent version: ${current_version}\033[0m"  # Print in green
  print-version-in-other-job:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: print
        id: test
        run: echo "v${{ steps.read-current-app-json.outputs.current_version }} from output"
             echo "v${{ needs.check-version.outputs.current_version }} from needs"