name: Build and Deploy Docker Images

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'app.json'
      - 'docker-compose/docker-compose.yml'
      - '.github/workflows/ci.yml'
env:
  NODE_VERSION: '20'
jobs:
  check-updated-version:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_APP_VERSION: ${{ steps.read-current-app-json.outputs.CURRENT_APP_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current app.json version
        id: read-current-app-json
        run: |
          CURRENT_APP_VERSION=$(jq -r '.version' ./app.json)
          echo "CURRENT_APP_VERSION=${CURRENT_APP_VERSION}" >> $GITHUB_OUTPUT
          echo "CURRENT_APP_VERSION=${CURRENT_APP_VERSION}" >> $GITHUB_ENV
          echo "CURRENT_APP_VERSION=${CURRENT_APP_VERSION}"

      - name: Read previous app.json version
        id: read-previous-app-json
        run: |
          git fetch origin main:refs/remotes/origin/main
          git show origin/main:app.json > previous_app.json
          PREVIOUS_APP_VERSION=$(jq -r '.version' previous_app.json)
          echo "PREVIOUS_APP_VERSION=${PREVIOUS_APP_VERSION}" >> $GITHUB_ENV
          echo "PREVIOUS_APP_VERSION=${PREVIOUS_APP_VERSION}"
          
      - name: Check if version has changed
        id: version_check
        run: |
          echo "CURRENT_APP_VERSION=$CURRENT_APP_VERSION"
          echo "PREVIOUS_APP_VERSION=$PREVIOUS_APP_VERSION"
          if [ "$CURRENT_APP_VERSION" != "$PREVIOUS_APP_VERSION" ]; then
            echo "Version has changed from $PREVIOUS_APP_VERSION to $CURRENT_APP_VERSION."
          else
            echo "Version isn't updated."
            exit 1
          fi
  
  check-docker-compose-version:
    runs-on: ubuntu-latest
    needs: check-updated-version
    env: 
      CURRENT_APP_VERSION: ${{needs.check-updated-version.outputs.CURRENT_APP_VERSION}}
    outputs:
      DOCKER_VERSION: ${{ steps.read-docker-compose.outputs.DOCKER_VERSION }}
      FRONTEND_IMAGE_VERSION: ${{ steps.read-docker-compose.outputs.FRONTEND_IMAGE_VERSION }}
      BACKEND_IMAGE_VERSION: ${{ steps.read-docker-compose.outputs.BACKEND_IMAGE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read docker-compose.yml
        id: read-docker-compose
        run: |
          DOCKER_VERSION=$(grep "version:" docker-compose/docker-compose.yml | awk '{print $2}' | tr -d "'")
          FRONTEND_IMAGE_VERSION=$(grep "image: ${{ secrets.DOCKER_USERNAME }}/incnv-frontend:" docker-compose/docker-compose.yml | awk -F: '{print $3}')
          BACKEND_IMAGE_VERSION=$(grep "image: ${{ secrets.DOCKER_USERNAME }}/incnv-backend:" docker-compose/docker-compose.yml | awk -F: '{print $3}')

          echo "DOCKER_VERSION=$DOCKER_VERSION"
          echo "FRONTEND_IMAGE_VERSION=$FRONTEND_IMAGE_VERSION"
          echo "BACKEND_IMAGE_VERSION=$BACKEND_IMAGE_VERSION"

          echo "DOCKER_VERSION=$DOCKER_VERSION" >> $GITHUB_OUTPUT
          echo "DOCKER_VERSION=$DOCKER_VERSION" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_VERSION=$FRONTEND_IMAGE_VERSION" >> $GITHUB_OUTPUT
          echo "BACKEND_IMAGE_VERSION=$BACKEND_IMAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Check matched version
        run: |
          if [[ "$CURRENT_APP_VERSION" == "$DOCKER_VERSION" ]]; then
            echo "CURRENT_APP_VERSION is equal to DOCKER_VERSION"
          else
            echo "CURRENT_APP_VERSION isn't equal to DOCKER_VERSION"
            exit 1
          fi

  install-and-build-frontend:
    runs-on: ubuntu-latest
    needs: [check-docker-compose-version]
    env:
      FRONTEND_IMAGE_VERSION: ${{needs.check-docker-compose-version.outputs.FRONTEND_IMAGE_VERSION}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Init frontend submodule
        run: |
            git submodule update --init frontend
            cd frontend
            git submodule update --init --recursive
            git fetch --tags
            git checkout v${FRONTEND_IMAGE_VERSION}

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend project
        run: npm run build
        working-directory: ./frontend

  install-and-build-backend:
    runs-on: ubuntu-latest
    needs: [check-docker-compose-version]
    env:
      BACKEND_IMAGE_VERSION: ${{needs.check-docker-compose-version.outputs.BACKEND_IMAGE_VERSION}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Init backend submodule
        run: |
            git submodule update --init backend
            cd backend
            git submodule update --init --recursive
            git fetch --tags
            git checkout v${BACKEND_IMAGE_VERSION}

      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Build backend project
        run: npm run build
        working-directory: ./backend
      
  create-frontend-image:
    runs-on: ubuntu-latest
    needs: [check-docker-compose-version, install-and-build-frontend]
    env:
      FRONTEND_IMAGE_VERSION: ${{needs.check-docker-compose-version.outputs.FRONTEND_IMAGE_VERSION}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Init frontend submodule
        run: |
            git submodule update --init frontend
            cd frontend
            git submodule update --init --recursive
            git fetch --tags
            git checkout v${FRONTEND_IMAGE_VERSION}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push incnv-frontend Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/incnv-frontend:${FRONTEND_IMAGE_VERSION} -t ${{ secrets.DOCKER_USERNAME }}/incnv-frontend:latest ./frontend --push

  create-backend-image:
    runs-on: ubuntu-latest
    needs: [check-docker-compose-version, install-and-build-backend]
    env:
      BACKEND_IMAGE_VERSION: ${{needs.check-docker-compose-version.outputs.BACKEND_IMAGE_VERSION}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Init backend submodule
        run: |
            git submodule update --init backend
            cd backend
            git submodule update --init --recursive
            git fetch --tags
            git checkout v${BACKEND_IMAGE_VERSION}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push incnv-backend Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/incnv-backend:${BACKEND_IMAGE_VERSION} -t ${{ secrets.DOCKER_USERNAME }}/incnv-backend:latest ./backend --push

          
  add-tag-version:
    runs-on: ubuntu-latest
    needs: [check-updated-version, create-frontend-image, create-backend-image]
    env:
      CURRENT_APP_VERSION: ${{ needs.check-updated-version.outputs.CURRENT_APP_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch tags from remote
        run: git fetch --tags

      - name: Check if tag already exists
        id: tag-check
        run: |
          if git rev-parse "v${CURRENT_APP_VERSION}" >/dev/null 2>&1; then
            echo "Tag v${CURRENT_APP_VERSION} already exists."
            echo "IS_TAG_EXIST=true" >> $GITHUB_OUTPUT
          else
            echo "Tag v${CURRENT_APP_VERSION} does not exist."
            echo "IS_TAG_EXIST=false" >> $GITHUB_OUTPUT
          fi

      - name: Create tag if not exists
        if:  steps.tag-check.outputs.IS_TAG_EXIST == 'false' 
        run: |
          git tag "v${CURRENT_APP_VERSION}"
          git push origin "v${CURRENT_APP_VERSION}"
          echo "Add tag v${CURRENT_APP_VERSION} finished."